# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b1ef78b0c222112052393afd913da884956c61b5958eda3b15a63080a2b8ae3f7d604749199e93d12aeba0e8e232048e06dc013588095393af986af470007c

test:
  secret_key_base: 165abcac4331d1b139c487f5bbec0e795d020b6442db425922b8ec56cb5fc505a09180d2a74b59c331fc52f9cbdbb4024fc63bc3b36d305eb45ffc26e8b66bcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
